// Code generated by https://gotool.top
package model

import "time"

// Transfers 转账记录表
type Transfers struct {
	TransferId   int32     `gorm:"column:transfer_id;primary_key;NOT NULL;comment:'转账记录ID'"`
	FromWalletId int32     `gorm:"column:from_wallet_id;NOT NULL;comment:'转出钱包ID'"`
	ToWalletId   int32     `gorm:"column:to_wallet_id;NOT NULL;comment:'转入钱包ID'"`
	Amount       int64     `gorm:"column:amount;type:bigint;default:0;comment:'转账金额(分)'"`
	CreatedAt    time.Time `gorm:"column:created_at;autoCreateTime;default:CURRENT_TIMESTAMP;comment:'转账时间'"`
}

// TableName 表名
func (t *Transfers) TableName() string {
	return "transfers"
}
