// Code generated by https://gotool.top
package model

import (
	"time"
)

// Wallets 钱包表
type Wallets struct {
	WalletId  int32     `gorm:"column:wallet_id;primary_key;NOT NULL;comment:'钱包ID'"`
	UserId    int64     `gorm:"column:user_id;default:NULL;comment:'用户ID'"`
	Balance   int64     `gorm:"column:balance;type:bigint;default:0;comment:'余额(分)'"`
	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime;default:CURRENT_TIMESTAMP;comment:'创建时间'"`
}

// TableName 表名
func (w *Wallets) TableName() string {
	return "wallets"
}
